export const content = {
  name: "Michael Hong",
  tagline:
    "Business Administration Major with a concentration in Information Systems and a Minor in Music. I'd love to combine my business expertise with my passion for music to make a meaningful impact working in music technology.",
  email: "michaelhonggsq@gmail.com",
  linkedin: "https://www.linkedin.com/in/michaelhong170/",
  instagram: "https://www.instagram.com/michael.honggg/",

  about: {
    bio: "My name is Michael Hong and I'm a third year business student at Cal Poly! I'm from Dublin, California (Bay Area) and I'd love to work in the music industry when I'm older, more specifically music technology. I will be interning at Protiviti in San Francisco this summer as a technology consulting intern, and in my free time I like to go to the gym, play music, and go on spontaneous adventures!",
    highlights: [
      "3.87 GPA — Dean's List 8x, President's List 2x",
      "Incoming Technology Consulting Intern at Protiviti (June 2026)",
      "Amazon Area Manager Intern — oversaw 110+ associates across fulfillment operations",
      "President of OCOB Student Ambassadors, representing 3,000+ students",
      "Executive Vice-President of Alpha Kappa Psi Business Fraternity",
    ],
  },

  education: [
    {
      school: "California Polytechnic State University",
      location: "San Luis Obispo, CA",
      degree: "B.S. Business Administration: Information Systems | Minor: Music",
      dates: "Sept. 2023 – Jun. 2027",
      logo: "/logos/calpoly.jpeg",
      bullets: [
        "GPA: 3.87",
        "Honors: Dean's List 8x, President's List 2x",
        "Relevant Coursework: Database Systems in Business (SQL), Project Management, Business Application Development",
      ],
    },
  ],

  experience: [
    {
      title: "Technology Consulting Intern",
      company: "Protiviti",
      location: "San Francisco, CA",
      dates: "June 2026 – Present",
      logo: "/logos/protiviti.jpeg",
      photos: [] as string[],
      bullets: [
        "Drive digital transformation through implementation of technology, enhancing operational efficiency within businesses",
      ],
    },
    {
      title: "Lead Social Media Marketing Intern",
      company: "Tifa Chocolate & Gelato",
      location: "Walnut Creek, CA",
      dates: "Feb. 2026 – Present",
      logo: "/logos/tifa.jpeg",
      photos: [] as string[],
      bullets: [
        "Scaled Instagram to 366 new followers and 138K+ views in 3.5 months through strategic content creation",
        "Synthesized Meta analytics using Claude AI to generate weekly performance reports and data-driven insights",
        "Leveraged Claude AI for scripting, editing, and end-to-end video production to drive engagement",
      ],
    },
    {
      title: "Peer Mentor",
      company: "Orfalea College of Business",
      location: "San Luis Obispo, CA",
      dates: "Apr. 2024 – Jun. 2026",
      logo: "/logos/ocob.jpeg",
      photos: [] as string[],
      bullets: [
        "Mentor and guide four students bi-weekly through goal setting and motivational interviewing, ensuring personal success",
        "Collaborate with 80+ students in OCOB student services to provide resources and opportunities to mentees",
        "Synthesize student feedback and academic progress to tailor mentoring strategies and improve outcomes",
      ],
    },
    {
      title: "Recruitment Ambassador",
      company: "California Polytechnic State University (Cal Poly)",
      location: "San Luis Obispo, CA",
      dates: "Sep. 2025 – Mar. 2026",
      logo: "/logos/calpoly.jpeg",
      photos: [] as string[],
      bullets: [
        "Executed large-scale recruitment events with admissions staff, supporting diversity, equity, and inclusion initiatives",
        "Coordinated 60+ members in the Mustang Mentorship Program, coordinating bi-monthly meetings and quarterly events",
        "Utilized Slate to verify thousands of forms and streamline digital workflows for on-campus events",
      ],
    },
    {
      title: "Campus Events Launcher",
      company: "DoorDash",
      location: "San Luis Obispo, CA",
      dates: "Aug. 2024 – Dec. 2025",
      logo: "/logos/doordash.jpeg",
      photos: [] as string[],
      bullets: [
        "Executed 40+ events driving 2,200+ Student DashPass signups, increasing market share and revenue",
        "Built and established ongoing partnerships with 7+ student organizations, growing external signups by 12%",
        "Streamlined event planning processes to improve efficiency and scalability of campus initiatives",
      ],
    },
    {
      title: "Campus Growth Director",
      company: "Leland",
      location: "San Luis Obispo, CA",
      dates: "Sep. 2025 – Dec. 2025",
      logo: "/logos/leland.png",
      photos: [] as string[],
      bullets: [
        "Led 12+ ambassadors to drive 250 Leland+ signups, unlocking $7.6M in resources for 22,000 Cal Poly undergrads",
        "Placed 1st out of 120+ ambassadors for student org partnerships and ambassador recruiting in a two-week sprint",
        "Partnered with Leland's $20M Series A team to shape the ambassador program and refine campus growth strategy",
      ],
    },
    {
      title: "Social Lead Ambassador",
      company: "Acorns",
      location: "San Luis Obispo, CA",
      dates: "Sept. 2025 – Dec. 2025",
      logo: "/logos/acorns.jpeg",
      photos: [] as string[],
      bullets: [
        "Managed on-campus marketing events promoting financial literacy tools, securing 600+ new user clickthroughs",
        "Identified high-traffic event locations and coordinated tabling logistics to educate students on platform benefits",
        "Partnered with on-campus organizations, including DoorDash, to amplify outreach through joint tabling events",
      ],
    },
    {
      title: "Area Manager Intern",
      company: "Amazon",
      location: "Tracy, CA",
      dates: "Jun. 2025 – Aug. 2025",
      logo: "/logos/amazon.jpeg",
      photos: [] as string[],
      bullets: [
        "Oversaw operations of 110+ associates in AFE1 maintaining individual productivity of 1,500+ items packed daily",
        "Implemented an upgrade box chart, minimizing the SLAM Wrong Box defect rate, the site's third-most common defect",
        "Conducted data analysis using Tableau and Excel to identify inefficiencies and implement process improvements",
      ],
    },
    {
      title: "Week of Welcome Orientation Leader",
      company: "California Polytechnic State University (Cal Poly)",
      location: "San Luis Obispo, CA",
      dates: "Apr. 2024 – Sep. 2024",
      logo: "/logos/calpoly.jpeg",
      photos: [] as string[],
      bullets: [
        "Led a group of 19+ freshmen through college orientation week, serving as representative student ambassador to the university",
        "Attended 30+ hours of training to gain personal, professional & leadership development",
        "Facilitated conversations on important topics about empathy and diversity, equity, & inclusion",
      ],
    },
    {
      title: "Program Director",
      company: "Skyhawks Sports Academy",
      location: "San Francisco Bay Area",
      dates: "Jun. 2024 – Aug. 2024",
      logo: "/logos/skyhawks.jpeg",
      photos: [] as string[],
      bullets: [
        "Managed daily game plans, activities, and lessons for 30+ campers aged 6-12, collaborating with assistant coaches",
        "Fostered an engaging learning environment by teaching fundamentals for major sports including basketball and track",
        "Maintained effective communication with managers, head, and assistant coaches while adjusting to unknown circumstances",
      ],
    },
  ],

  leadership: [
    {
      title: "President",
      org: "Orfalea College of Business Student Ambassadors",
      location: "San Luis Obispo, CA",
      dates: "May 2026 – Present",
      logo: "/logos/ocob.jpeg",
      bullets: [
        "Selected as 1 of 32 students to be the external-facing student leadership group representing OCOB (3,000+ students)",
        "Manage tours for 1,000+ prospective students and synthesize feedback to improve program effectiveness",
        "Lead communication and coordination across digital productivity tools to enhance team efficiency",
      ],
    },
    {
      title: "Executive Vice-President",
      org: "Alpha Kappa Psi Business Fraternity",
      location: "San Luis Obispo, CA",
      dates: "Apr. 2025 – Mar. 2026",
      logo: "/logos/akpsi.jpeg",
      bullets: [
        "Led executive board (17+ members) in executing professional and philanthropic initiatives for 80+ members",
        "Managed $10K quarterly budget and supported strategic decision making at the organizational level",
        "Standardized internal systems and communication processes to improve collaboration and planning",
      ],
    },
  ],

  gallery: [
    "/About Me Page/gallery photos/260527-APP-1078_w.jpg",
    "/About Me Page/gallery photos/DSC00197.jpeg",
    "/About Me Page/gallery photos/DSCF3744 (1).jpeg",
    "/About Me Page/gallery photos/IMG_0797.jpeg",
    "/About Me Page/gallery photos/IMG_1739.jpeg",
    "/About Me Page/gallery photos/IMG_1940.jpeg",
    "/About Me Page/gallery photos/IMG_2346.jpeg",
    "/About Me Page/gallery photos/IMG_2576.jpeg",
    "/About Me Page/gallery photos/IMG_2750.jpeg",
    "/About Me Page/gallery photos/IMG_2774.jpeg",
    "/About Me Page/gallery photos/IMG_3121.jpeg",
    "/About Me Page/gallery photos/IMG_3157.jpeg",
    "/About Me Page/gallery photos/IMG_3437.jpeg",
    "/About Me Page/gallery photos/IMG_3602.jpeg",
    "/About Me Page/gallery photos/IMG_5838.jpeg",
    "/About Me Page/gallery photos/IMG_6331.jpeg",
    "/About Me Page/gallery photos/IMG_8239.jpeg",
    "/About Me Page/gallery photos/IMG_9313.jpeg",
  ],

  skills: ["Microsoft Office Suite (Excel, Outlook)", "Tableau", "Canva", "Claude AI", "PowerPoint", "Slack", "Zoom"],

  interests: [
    { name: "Calisthenics",        type: "image", src: "", photos: [] as string[], description: "Ever since I finished my running journey in high school, I knew I wanted to get into calisthenics. My dream skill is the front lever, and I started training in the summer of 2025. Still struggling to balance a hand stand, it's a lot harder than I thought :(" },
    { name: "Guitar",              type: "image", src: "", photos: [] as string[], description: "I took a guitar class in middle school and fell in love. After the class ended I started taking lessons from a college student, and after 6 months I started teaching myself. My dad bought a 12 string guitar from an auction which we later sold so I could buy my first ever electric guitar." },
    { name: "Piano",               type: "image", src: "", photos: [] as string[], description: "I started learning piano in elementary school and took lessons all the way up until freshman year of high school, until COVID unfortunately cut my piano lessons short. I enjoy playing classical and pop music, and have started experimenting with songwriting originally on the piano." },
    { name: "Running",             type: "image", src: "", photos: [] as string[], description: "I started running cross country and track and field in middle school. I fell in love with the running community and ran all four years of high school. Favorite workout: Hill Repeats. Favorite race: 800 meter." },
    { name: "Singing/Songwriting", type: "image", src: "", photos: [] as string[], description: "In high school I started experimenting with creating music using LMMS and BandLab. I also played in a band called Late Spring, and we released a song on Spotify called \"over u\" (GO LISTEN). More recently in college I've learned Logic Pro and Ableton, and have continued to study music theory and jazz over the last couple years." },
    { name: "Soccer",              type: "image", src: "", photos: [] as string[], description: "I've played soccer from 1st grade all the way through my senior year of high school. What once started as a sport my mom signed me up for without my knowledge, it has since become one of my favorite physical activities. Messi > Ronaldo" },
  ],
};
